### ISSUE TITLE
3.5.3 Exercisesの課題について

### ISSUE THREAD

**Issue by ryoma123** [ryoma123/sample_app2#4]
@tacahilo @kitak @gs3 @keokent
### 3.5.3 Exercisesの課題

下記のエラーで悩んでいるのですが、アドバイスをいただきたく思います、、！
- エラー画面

![2014-07-09 18 12 36](https://cloud.githubusercontent.com/assets/1731974/3522173/3e979ec8-0749-11e4-8fa4-57f4b644964c.png)
### やったこと

sample_appのアプリケーションのデータベースをsplite3→postgreSQLに変更したい！
- [x] Gemfile の修正（sqlite3 gem → pg gem）
- [x] postgreSQLをインストール
- [x] config/database.yml の修正（間違っているかも、、）
### 設定など
- config/database.yml

```
development:
  adapter: postgresql
  encoding: unicode
  database: db/development.postgresql
  pool: 5
  username: ryoma
  password: test109274089

test:
  adapter: postgresql
  encoding: unicode
  database: db/development.postgresql
  pool: 5
  username: ryoma
  password: test109274089

production:
  adapter: postgresql
  encoding: unicode
  database: db/development.postgresql
  pool: 5
  username: ryoma
  password: test109274089
```
